### ISSUE TITLE
Web API and Authorize with Roles

### ISSUE THREAD

**Issue by kyleboucherlancom** [JudahGabriel/RavenDB.Identity#1]
When using this with an API project in a SPA I'm having trouble locking down certain end points to specific roles. 

1. When the [Authorize] attribute denies a request it tries to redirect the 401 to the "Account/Login" page. As I'm using a SPA and an API how do I stop this so it correctly returns 401 from the api call?

I've tried adding this to the Startup file to convert the api redirects to 401, however it doesn't work correctly. 
```
    services.AddAuthentication(opts =>
                {
                    opts.DefaultAuthenticateScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                    opts.DefaultChallengeScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                })
                .AddCookie(opts =>
                {
                    opts.Cookie.Name = ".AspNetCore.Identity.Application";
                    opts.Events = new CookieAuthenticationEvents()
                    {
                        
                        OnRedirectToLogin = ctx =>
                        {
                            if (ctx.Request.Path.StartsWithSegments("/api") && ctx.Response.StatusCode == 200)
                            {
                                ctx.Response.StatusCode = 401;
                                return Task.FromResult<object>(null);
                            }

                            ctx.Response.Redirect(ctx.RedirectUri);
                            return Task.FromResult<object>(null);
                        }
                    };
                });
```

2. It correctly authorizes when not logged in, or logged in. But when I add [Authorize(Roles = "ADMIN")] I can no longer access this route because of being unauthorized.

My user is in the "ADMIN" role, I have confirmed in the RavenDB that the user has this set in the Roles array.
`await _userManager.AddToRoleAsync(user, "ADMIN");`

**Comment by JudahGabriel** [comment]
Hmm. I'll have a look at this now and get back to you.

**Comment by JudahGabriel** [comment]
OK, for the first problem, inside Startup.cs, you can change the login path like this:

```
public void ConfigureServices(IServiceCollection services)
{
    ...
    services.ConfigureApplicationCookie(options => options.LoginPath = "/my/login/path");
}
```

But for #2, I'm investigating the issue. I should have an answer for you today.

**Comment by JudahGabriel** [comment]
I've fixed the 2nd issue and published to NuGet. Authorization will now correctly and check for roles as of RavenDB.Identity 2.1.

@kyleboucherlancom To fix your situation:
1. Upgrade to the latest RavenDB.Identity NuGet package
2. Remove any .Roles from your users. 
3. Add users to roles via `userManager.AddToRoleAsync(user, "Admin")`

**Comment by kyleboucherlancom** [comment]
@JudahGabriel Thank you for the quick support! Everything is working as I would expect it to now.
