### ISSUE TITLE
UserStore<T>MigrateToV6() does not work for DocumentStore with Conventions.FindCollectionName set

### ISSUE THREAD

**Issue by abremora** [JudahGabriel/RavenDB.Identity#11]
We initialize our stores like that, because we feel it is more natural:

```csharp
var store = new DocumentStore {
    Certificate = clientCertificate,
    Urls = new[] { url },
    Database = database,
    Conventions = {
        FindCollectionName = t => t.Name,
        UseOptimisticConcurrency = useOptimisticConcurrency
    }
};
store.Initialize();
```
So our documents start with `IdentityUserByUserName/`. But in UserStore<T>.MigrateToV6() the document prefix is hard coded:

https://github.com/JudahGabriel/RavenDB.Identity/blob/663c3fb7b754d0af23d45b7aee1f5f588db488c3/RavenDB.Identity/UserStore.cs#L806

Maybe the best would be an overloaded method to set the prefix manually.

**Comment by JudahGabriel** [comment]
This is fixed and merged.
