### ISSUE TITLE
Register User: The email address ... is already taken.

### ISSUE THREAD

**Issue by zardos2191** [JudahGabriel/RavenDB.Identity#20]
Hi,

when I register a new User, the user is created and it works well.
After that I deleted this User in the RavenDB. Then I tried to Register the same email adress again, and it fails telling me:  "The email address ... is already taken."
How is this possible, after i deleted the User in the database? I restarted the database and the demo application, but the email adress cannot be registered again. Is there anything I did wrong?

Thanks in advance, keep up your good work! 
Bye

**Comment by zardos2191** [comment]
By the way: It would be awesome if you could introduce the correct usage of the RoleManager into your demo application.

**Comment by JudahGabriel** [comment]
Deleting the user in the database isn't enough. 

You also need to go into Compare Exchange and delete it there:
![image](https://user-images.githubusercontent.com/312936/69194111-2d2a0480-0add-11ea-82f9-c7fec7bd6058.png)

This is required for making Identity work in a cluster.
