### ISSUE TITLE
How to handle unique constraints in a user?

### ISSUE THREAD

**Issue by cadilhac** [JudahGabriel/RavenDB.Identity#28]
Hi,

I'm new to both asp.net core identity and your project and I was wondering how to tackle the need for unique constraints, for example for the username. At what level can it be done?
Thanks

**Comment by JudahGabriel** [comment]
In short, you don't have to do anything on the backend. RavenDB.Identity will enforce email-based uniqueness on the cluster level. If a user tries to register with an already-registered email address, the 2nd attempt will fail.

Does that answer your question?

**Comment by cadilhac** [comment]
No ;)
I know that you take care about email uniqueness. My question is about having some other fields unique, in particular the username.

**Comment by cadilhac** [comment]
And the question can be extended to a field that is not in the user's base class. It's not my use case, but it could be a custom field that I will add in my user's derived class.

**Comment by cadilhac** [comment]
Good idea. I can encapsulate the call to your API with a reserve, and unreserve if it failed.
