### ISSUE TITLE
User Id configuration not consistent with RavenDB

### ISSUE THREAD

**Issue by marcuslindblom** [JudahGabriel/RavenDB.Identity#31]
Is it possible to configure the id generation to auto generate ids rather then server generated? I Prefer `users/1-A` rather then `users/0000000000000001074-A`.

I use `services.Configure<RavenIdentityOptions>(options => options.UserIdType = UserIdType.ServerGenerated);` but according to the docs the id should be in the auto generated format rather then server generated.

<img width="600" alt="Screenshot 2020-07-26 at 09 53 50" src="https://user-images.githubusercontent.com/319720/88474379-0bafd100-cf26-11ea-9800-dbbd86bd5184.png">
 
IMO RavenDB.Identity should be more consistent with how RavenDB works.

If I add `users|` to my `Users` class like this

```c#
public class User : Raven.Identity.IdentityUser {
    public User() {
        Id = "users|";
    }
}
```

I expect the Id to be `users/1` not `users/0000000000000001074-A` but that does not work either?

**Comment by JudahGabriel** [comment]
Thanks for the feedback. I'll see what can be done.

If you configure Raven.Identity to use Server generated IDs, it sets the ID to "Users/", then let's Raven take care of the rest. This, "Users/0000000012-A" is coming from Raven.

**Comment by marcuslindblom** [comment]
I think setting `Id = null` would generate ids like `users/1-A`. `Id = string.Empty` will generate a GUID id. `Id = "Users/"` will generate `Users/0000000012-A` and `Id = "Users|"` will generate `users/1`. See docs [here](https://ravendb.net/docs/article-page/4.2/csharp/client-api/document-identifiers/working-with-document-identifiers) to make it more consistent with RavenDB. If you decide it's a good idea 💡

**Comment by marcuslindblom** [comment]
Without knowing the details maybe you could just remove the id handling and leave it to Raven?

If someone want, let's say username style they just do

```c#
store.Conventions.RegisterAsyncIdConvention<AppUser>(
    (dbname, user) =>
        Task.FromResult(string.Format("users/{0}", user.DisplayName)));
```

**Comment by JudahGabriel** [comment]
Yeah, the ID generation used to be important part of this library. This library was originally created by someone else, and they used email-based IDs as a way to prevent duplicates.

Unfortunately, that doesn't work in a cluster, so we changed the behavior to use compare/exchange to prevent duplicates. But the ID generation stuck around. 🤷‍♀️

You may be right, perhaps ID generation is best left to the user. I'll push an update in the coming week to allow for that.

**Comment by JudahGabriel** [comment]
p.s. I've been using Raven since 1.0...and I never knew about the pipe ID thing? How did I miss that? 😮 Thanks for teaching me something new.

**Comment by marcuslindblom** [comment]
I'm happy to help 😀

**Comment by cadilhac** [comment]
> p.s. I've been using Raven since 1.0...and I never knew about the pipe ID thing? How did I miss that? 😮 Thanks for teaching me something new.

I think it only got introduced in 4.0

**Comment by JudahGabriel** [comment]
I'll accept that explanation since it makes me appear less ignorant. 😉

**Comment by JudahGabriel** [comment]
Ok, I've published Raven.Identity v8.0.2 which rids us of the custom ID stuff. We now just use whatever Id Raven assigns to the user, or use what you've supplied to the user when you create the user. (Including support for "users|".)

I've also update the migration to change existing IDs. Raven.Identity can work with old user IDs or new, doesn't matter - but you can run the migration if you want consistency in your user IDs.

**Comment by cadilhac** [comment]
I see that you have version numbers. This would be great if you publish releases on github.

**Comment by JudahGabriel** [comment]
Those versions I refer to are Nuget package versions.

**Comment by marcuslindblom** [comment]
Great news and well done @JudahGabriel 👍🏻
