### ISSUE TITLE
How to change Email-Adress (with CompareExchange)

### ISSUE THREAD

**Issue by oiBio** [JudahGabriel/RavenDB.Identity#35]
Hi, is there an implemented way to change a users Email-Adress include the changecompare key?
We allow the user to change his/her email, but after that he can not login anymore

**Comment by oiBio** [comment]
Okay... just re-read the source code. its already implemented in UpdateUser.
My bad sorry.

**Comment by JudahGabriel** [comment]
Yep, UpdateUser will do the right thing, including updating the compare/exchange key if necessary.
