### ISSUE TITLE
Add Login

### ISSUE THREAD

**Issue by thaleshs** [JudahGabriel/RavenDB.Identity#4]
I know the problem is with the UserLoginInfo class. But how to solve this?

An unhandled exception occurred while processing the request.
PlatformNotSupportedException: This instance contains state that cannot be serialized and deserialized on this platform.
System.Security.Claims.ClaimsPrincipal.OnSerializingMethod(StreamingContext context)

TargetInvocationException: Exception has been thrown by the target of an invocation.
System.RuntimeMethodHandle.InvokeMethod(object target, Object[] arguments, Signature sig, bool constructor)

**Comment by JudahGabriel** [comment]
What's the full stack trace?
