### ISSUE TITLE
Consider using Raven compare/exchange to ensure uniqueness

### ISSUE THREAD

**Issue by JudahGabriel** [JudahGabriel/RavenDB.Identity#5]
We're currently relying on unique doc IDs to ensure non-duplicate emails/usersnames.

That's fine for a single database, but may not work in a cluster. Thus, we should use [Raven compare/exchange](https://ravendb.net/docs/article-page/4.1/csharp/client-api/operations/compare-exchange/overview) to ensure uniqueness.

If we do that, we probably will no longer need IdentityUsersByUserName.

**Comment by marcuslindblom** [comment]
Are you still considering to change this?

**Comment by JudahGabriel** [comment]
Yes. I'll see if I can make this happen this week.

**Comment by JudahGabriel** [comment]
Implemented. RavenDB.Identity v6 now uses compare/exchange to ensure email address uniqueness across clusters.

This has two side-effects, one good and one bad:

- The good: We no longer store 2 entities per user; IdentityUserByUserName is obsolete. You can safely delete this collection.
- The bad: If you were using a previous version of RavenDB.Identity and you're upgrading to v6 or later, you *must* call `UserStore<AppUser>.MigrateToV6(docStore)`. Failure to do so will result in your users not being able to login. The `MigrateToV6` method creates a compare/exchange value for each email address.
