### ISSUE TITLE
Delegate to modify conventions

### ISSUE THREAD

**Issue by esenciadev** [JudahGabriel/RavenDB.Identity#7]
Method to add the document store needs to take a delegate that can modify conventions on the doc store before it is initialized

**Comment by JudahGabriel** [comment]
You're right, we should have this. And now we do.

The .AddRavenDbDocStore is actually from [RavenDB.DependencyInjection](https://github.com/judahgabriel/ravendb.dependencyinjection), and RavenDB.Identity just uses that.

I've updated that code and published and update to NuGet. If you update RavenDB.DependencyInjection NuGet package, you'll have a .AddRavenDbDocStore(store => ...) call. The configuration action is called just before initialization.

**Comment by JudahGabriel** [comment]
Just a small update here, we're pushing out a new update that changes this call slightly. The new call is:

```csharp
// Run our configAction delegate before initialization
services.AddRavenDbDocStore(options => options.BeforeInitializeDocStore(configAction));
```
