### ISSUE TITLE
Default Identity - considerations

### ISSUE THREAD

**Issue by AlphaComposite** [JudahGabriel/RavenDB.Identity#9]
Now that this project has switched to Razor from MVC, it makes sense that there should be a non-default identity scaffold project so that users can customize the files without figuring out how to generate them. The "hidden" scaffold identity files are more of a nuisance than helpful as most people aren't going to use the project as a starting point without being able to modify the files. 

Here's Microsoft's documentation on the subject: 
https://docs.microsoft.com/en-us/aspnet/core/security/authentication/scaffold-identity?view=aspnetcore-2.2&tabs=netcore-cli

Thoughts?

**Comment by JudahGabriel** [comment]
To be clear, this project works with any ASP.NET Core project - Razor, MVC, whatever. The sample project uses Razor Pages.

I realize Razor pages hides the implementation. Perhaps we revert back to using MVC for the sample project.

**Comment by AlphaComposite** [comment]
Yes, I'm with you on that. I was just speaking about the Sample site for customization's sake. I generated the Razor Identity files and cleared all the errors. Registration is working, but login isn't. I was wondering if you might want these Razor files after I figure out why the login isn't working - or you could probably figure it out faster. 

Maybe give people MVC and Razor Sample projects? That'd be beneficial to the community.

**Comment by JudahGabriel** [comment]
I agree, we should provide MVC and Razor samples. I'll add an MVC sample and then close this issue.

**Comment by AlphaComposite** [comment]
How did you want to handle the Razor sample? Just using the "hidden" default scaffolding? Or should we include the files?

**Comment by JudahGabriel** [comment]
I’m opened to suggestions. You’re leaning having them visible?

**Comment by prince272** [comment]
I've rewritten the Asp Core Identity for Mvc. Feel free to take a look at https://github.com/prince272/AspCoreIdentityMvc

Simply change the url for the area 'Identity' to 'IdentityMvc' and you'll be automatically directed to the Mvc version for Identity.

**Comment by AlphaComposite** [comment]
> I’m opened to suggestions. You’re leaning having them visible?

I think this makes sense so that people can modify the files for their own needs without having to generate the files first and then rework the project to work with the generated files.

**Comment by JudahGabriel** [comment]
OK, I'll aim to have both an MVC and Razor Pages sample, each with the registration / login stuff visible and editable.

**Comment by JudahGabriel** [comment]
We now have an [MVC sample](https://github.com/JudahGabriel/RavenDB.Identity/tree/master/Samples/Mvc) that includes all the pages. OK if I close this? Or do you want to see the Razor Pages sample with these as well?
